version: '3'
services:
  app:
    container_name: botanik_app
    build:
      context: ./php
    volumes:
      - './app/:/var/www/html'
      - './sites:/etc/apache2/sites-enabled'
      - './data/dev:/home/dev'
    links:
      - db
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    ports:
      - 8080:80
    networks:
      app_net:
        ipv4_address: 172.16.1.12
  db:
    container_name: botanik_db
    image: 'mysql:5.7'
    volumes:
      - './base:/var/lib/mysql'
      - './sql:/home/sql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    networks:
      app_net:
        ipv4_address: 172.16.1.11
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
